### ISSUE TITLE
FormBuilderSearchableDropdown error when inputing text

### ISSUE THREAD

**Issue by nicks258** [flutter-form-builder-ecosystem/form_builder_extra_fields#9]
Facing issue when I started typing in **FormBuilderSearchableDropdown**. Throwing error - 
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Builder(dirty):
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

The relevant error-causing widget was: 
  GetMaterialApp GetMaterialApp:file:///C:/Users/Others/AndroidStudioProjects/flutter-starter/lib/main.dart:56:14
When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4153:9)
flutter-form-builder-ecosystem/flutter_form_builder#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4167:6)
flutter-form-builder-ecosystem/flutter_form_builder#2      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4252:12)
flutter-form-builder-ecosystem/flutter_form_builder#3      InheritedTheme.capture (package:flutter/src/widgets/inherited_theme.dart:102:10)
flutter-form-builder-ecosystem/flutter_form_builder#4      InheritedTheme.captureAll (package:flutter/src/widgets/inherited_theme.dart:67:12)
flutter-form-builder-ecosystem/flutter_form_builder#5      _PopupMenuRoute.buildPage (package:dropdown_search/src/popupMenu.dart:473:29)
flutter-form-builder-ecosystem/flutter_form_builder#6      _ModalScopeState.build.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/routes.dart:872:55)
flutter-form-builder-ecosystem/flutter_form_builder#7      Builder.build (package:flutter/src/widgets/basic.dart:7398:48)
====================================================================================================
```
I am using following dependencies
flutter_form_builder: ^7.1.1
form_builder_extra_fields: ^7.1.0
 form_builder_validators: ^7.6.1.
Looking for quick help. Thanks(; @danvick @tjarvstrand

**Comment by deandreamatias** [comment]
Hi!
This is still an issue?
Can share a minimal example code please?
Thanks

**Comment by JohnGamal1** [comment]
in the last update 8.3, I can't figure out where is the search in the items field is like in version 7.1 FormBuilderSearchableDropdown

**Comment by deandreamatias** [comment]
@JohnGamal1 I don't understand your comment or even if is related with this issue

**Comment by JohnGamal1** [comment]
Sorry i thought it would be related,
In version 7.1 there was a search field in the dropdown, I can't find it any more in version 8

**Comment by deandreamatias** [comment]
Due to lack of response, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields
/issues/new/choose)
